version: "3.8"
services:
  order-service-api:
    build:
      context: .
    container_name: order-service-api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: ["make", "run"]
    networks:
      - app-shared-network

  db:
    image: postgres:16
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-shared-network

volumes:
  postgres_data:

networks:
  app-shared-network:
    external: true